### ISSUE TITLE
Uncaught TypeError: _this.handleUpdate is not a function

### ISSUE THREAD

**Issue by esmas-fdelpozo** [yianL/atom-spotified#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-spotified](https://github.com/yianL/atom-spotified) package, v0.1.1
### Stack Trace

Uncaught TypeError: _this.handleUpdate is not a function

```
At /Users/fdelpozo/.atom/packages/atom-spotified/lib/atom-spotified-view.coffee:106

TypeError: _this.handleUpdate is not a function
    at /Users/fdelpozo/.atom/packages/atom-spotified/lib/atom-spotified-view.coffee:106:22
    at /Users/fdelpozo/.atom/packages/atom-spotified/node_modules/spotify-node-applescript/lib/spotify-node-applescript.js:76:20
    at ChildProcess.<anonymous> (/Users/fdelpozo/.atom/packages/atom-spotified/node_modules/spotify-node-applescript/node_modules/applescript/lib/applescript.js:54:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.3
atom-beautify, v0.28.19
atom-spotified, v0.1.1
atom-wallaby, v1.0.7
docblockr, v0.7.3
editorconfig, v1.2.2
git-control, v0.4.0
history-tracker, v0.1.0
jshint, v1.8.3
minimap, v4.17.0
nucleus-dark-ui, v0.6.14
nuclide-file-watcher, v0.0.35
pigments, v0.19.2
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by yianL** [comment]
Hi @esmas-fdelpozo, thanks for reporting this error.
I suspected something, but wasn't able to reproduce on my machine. However I published a new version that could potentially fix this issue. Can you try upgrading to the latest version(0.1.2) and see if this error still exists?
