### ISSUE TITLE
Failed to activate the atom-spotified package

### ISSUE THREAD

**Issue by carrodher** [yianL/atom-spotified#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-spotified](https://github.com/yianL/atom-spotified) package 0.7.1

### Stack Trace

Failed to activate the atom-spotified package

```
At Cannot set property 'showStatus' of undefined

TypeError: Cannot set property 'showStatus' of undefined
    at Object.activate (main.js:16:5)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
     -0:03.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.compact-tab-bar.panel-shadows.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-atom-material-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-clock 0.1.6 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-spotified 0.7.1 
busy-signal 1.3.0 
docblockr 0.9.1 
file-icons 2.0.17 
git-time-machine 1.5.6 
goto-definition 1.2.0 
highlight-selected 0.12.0 
intentions 1.1.2 
language-docker 1.1.7 
language-latex 1.0.0 
language-tcl 0.1.2 
latex 0.42.3 
linter 2.1.0 
linter-chktex 1.3.0 
linter-docker 0.1.4 
linter-eslint 8.1.4 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-js-yaml 1.2.7 
linter-jsonlint 1.3.0 
linter-shellcheck 1.4.3 
linter-ui-default 1.2.1 
markdown-preview-plus 2.4.9 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.5.0 
minimap-linter 1.6.0 
minimap-selection 4.4.0 
multi-cursor 2.1.5 
pretty-json 1.6.1 
todo-show 1.11.0 
tree-view-git-status 1.3.1 
wakatime 6.0.13 
```

**Comment by yianL** [comment]
Maybe there's a breaking api change introduced in atom `1.16.0-beta0`? Will look into it sometime this week!

**Comment by yianL** [comment]
Hi @carrodher, Is this still an issue? I don't think I am able to reproduce. Also, I just published `v.0.8.0` today and it works with atom 1.17. Let me know if you still couldn't get this package to work.

**Comment by carrodher** [comment]
Hi, currently I was not using the package but I am thinking to install it again, thanks for taking a look.
