### ISSUE TITLE
Failed to load the atom-spotified package

### ISSUE THREAD

**Issue by timhecker** [yianL/atom-spotified#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-spotified](https://github.com/yianL/atom-spotified) package, v0.3.0
### Stack Trace

Failed to load the atom-spotified package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-spotified'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'atom-spotified'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/Luca/.atom/packages/atom-spotified/src/views/atom-spotified-view.js:93:25)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Luca/.atom/packages/atom-spotified/src/main.js:5:57)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:30)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  2x -1:22.4.0 core:close (atom-text-editor.editor.is-focused)
     -1:01.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:21 core:close (atom-text-editor.editor.mini.is-focused)
     -0:19.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.tinted-tab-bar.compact-tab-bar.panel-contrast.use-animations.compact-tree-view.blend-tree-view.theme-atom-material-syntax-dark.theme-atom-material-ui.has-custom-icons)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-scss-lint",
      "autocompile-jade"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
atom-material-syntax-dark, v0.2.5
atom-material-ui, v1.2.10
atom-spotified, v0.3.0
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.1
highlight-selected, v0.11.2
language-babel, v2.17.0
linter, v1.11.4
linter-eslint, v7.1.3
linter-jade, v0.3.2
linter-jshint, v2.0.4
linter-jsonlint, v1.2.2
linter-sass-lint, v1.3.0
minimap, v4.21.0
pigments, v0.26.0
project-manager, v2.9.7
react, v0.15.0
svg-preview, v0.7.4
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by yianL** [comment]
Restart Atom and the package should work again. This will be fixed in the up coming patch release (v0.3.1)
