### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by MJGTwo** [yianL/atom-spotified#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-spotified](https://github.com/yianL/atom-spotified) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/michaelgardner/.atom/packages/atom-spotified/src/utils/spotify-poller.js:74

TypeError: Cannot read property 'name' of undefined
    at /Users/michaelgardner/.atom/packages/atom-spotified/src/utils/spotify-poller.js:74:26
    at /Users/michaelgardner/.atom/packages/atom-spotified/node_modules/spotify-node-applescript/lib/spotify-node-applescript.js:74:24
    at ChildProcess.<anonymous> (/Users/michaelgardner/.atom/packages/atom-spotified/node_modules/spotify-node-applescript/node_modules/applescript/lib/applescript.js:54:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-pylint",
      "linter"
    ],
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-spotified, v0.3.1
chester-atom-syntax, v0.1.1
language-erlang, v3.0.0
language-haskell, v1.7.10
language-prolog, v0.10.0
minimap, v4.22.1

# Dev
No dev packages
```

**Comment by yianL** [comment]
Hi there, 
Thanks for trying out the package and reporting this error. Unfortunately I was unable to reproduce the error you're seeing. Judging from the stack trace, it's thrown from a line that only gets executed when the call to spotify api has failed. Let me know if you're still seeing this error or know of a way to reproduce it.
